# Generated by Django 5.2.3 on 2025-06-12 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingDate', models.DateField()),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('paymentStatus', models.IntegerField(default=0)),
                ('paymentType', models.CharField(max_length=100)),
                ('paymentAmount', models.IntegerField(default=0)),
                ('guestName', models.TextField()),
                ('guestEmail', models.CharField(max_length=50)),
                ('guestPhone', models.CharField(max_length=15)),
                ('guestAddress', models.TextField()),
                ('totalGuestsAdults', models.IntegerField(default=0)),
                ('totalGuestsChildren', models.IntegerField(default=0)),
                ('IDtype', models.CharField(max_length=30)),
                ('IDnumber', models.CharField(max_length=30, verbose_name='number on ID')),
                ('purposeOfStay', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('reviewDate', models.DateField()),
                ('rating', models.IntegerField()),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FarmHouse_Website.bookings')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsMedia',
            fields=[
                ('mediaId', models.AutoField(primary_key=True, serialize=False)),
                ('mediaType', models.CharField(max_length=20)),
                ('media', models.BinaryField()),
                ('reviewId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmHouse_Website.reviews')),
            ],
        ),
    ]
