# Generated by Django 5.2.3 on 2025-06-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmHouse_Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('dishId', models.AutoField(primary_key=True, serialize=False)),
                ('dishName', models.CharField(max_length=50)),
                ('dishDescription', models.TextField()),
                ('dishPrice', models.IntegerField()),
                ('dishImage', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='reviews',
            name='reviewContent',
            field=models.TextField(default=''),
        ),
    ]
