# Generated by Django 5.2.3 on 2025-06-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmHouse_Website', '0003_bookings_idimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsmedia',
            name='mediaName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
