# Generated by Django 5.2.3 on 2025-06-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmHouse_Website', '0004_reviewsmedia_medianame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='bookingId',
            field=models.IntegerField(),
        ),
    ]
